[env:adafruit_feather_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = adafruit_feather_esp32c6
framework = arduino

platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7.tar.xz
    framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.3.7/esp32-core-3.3.7-libs.tar.xz

lib_deps =
    adafruit/Adafruit EPD@4.6.13
    sensirion/Sensirion I2C SCD4x@1.1.0

monitor_speed = 115200
